apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rejekts-app
  namespace: production
spec:
  template:
    metadata:
      annotations:  
        dapr.io/app-id: rejekts-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true" 
        dapr.io/metrics-port: "9092"
    spec:
      containerConcurrency: 0
      containers:
        - image: ko://github.com/salaboy/rejekts-eu-2023/rejekts-app
          name: user-container
          livenessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/liveness
              port: 8080