apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-environment
spec:
  destination:
    name: in-cluster
    namespace: production
    server: ''
  source:
    path: production
    repoURL: 'https://github.com/salaboy/rejekts-eu-2023-gitops'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}